source 'https://github.com/cocoapods/specs.git'

platform :ios, '8.0'

xcodeproj 'Bequest'

def import_pods
    # UI
    pod 'SSDataSources', '0.8.0'
    pod 'pop'
    pod 'TTTAttributedLabel'
    pod 'JTSImageViewController'
    pod 'CYRTextView'

    # Networking
    pod 'Alamofire'
end

target :Bequest do
    import_pods
end

# Tests
target :BequestTests, :exclusive => true do
    import_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
end
