source 'https://github.com/cocoapods/specs.git'

platform :ios, '8.0'

xcodeproj 'Bequest'

def import_pods
    use_frameworks!

    # UI
    pod 'SSDataSources'
    pod 'pop'
    pod 'TTTAttributedLabel'
    pod 'JTSImageViewController'
    pod 'CYRTextView'
    pod 'SnapKit', :git => 'git@github.com:SnapKit/SnapKit.git', :branch => 'swift-2.0'

    # Networking
    pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift-2.0'
end

target :Bequest do
    import_pods
end

# Tests
target :BequestTests, :exclusive => true do
    import_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
end
