source 'https://github.com/cocoapods/specs.git'

platform :ios, '8.0'

xcodeproj 'Bequest'

def import_pods
    # UI
    pod 'SSDataSources', '0.8.0'
    pod 'Masonry'

    # Networking
    pod 'Alamofire', :git => "https://github.com/mrackwitz/Alamofire.git", :branch => "podspec"
end

target :Bequest do
    import_pods
end

# Tests
target :BequestTests, :exclusive => true do
    import_pods
    pod 'Quick', :git => "https://github.com/Quick/Quick"
    pod 'Nimble', :git => "https://github.com/Quick/Nimble"
end
